runtime: php55
api_version: 1
threadsafe: true
handlers:
- url: /test\.php.*
  script: test.php
  
- url: /fetch_video_url\.php.*
  script: fetch_video_url.php
  
- url: /fetch_file_name\.php.*
  script: fetch_file_name.php

- url: /.*
  script: fetch.php